
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores.json;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUM = 6;
  public static final int COMA = 2;
  public static final int LLAVE_END = 5;
  public static final int error = 1;
  public static final int STR = 7;
  public static final int LLAVE_START = 4;
  public static final int EOF = 0;
  public static final int DOS_PUNTOS = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "COMA",
  "DOS_PUNTOS",
  "LLAVE_START",
  "LLAVE_END",
  "NUM",
  "STR"
  };
}

