
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PARENTESIS_IZQ = 21;
  public static final int CHAR = 41;
  public static final int STR = 40;
  public static final int GRAFICAPIE = 49;
  public static final int CASE = 31;
  public static final int RESTA = 18;
  public static final int DOS_PUNTOS = 16;
  public static final int CORCHETE_DER = 27;
  public static final int FOR = 34;
  public static final int TITULOY = 51;
  public static final int WRITE = 38;
  public static final int TITULOX = 50;
  public static final int LLAVE_IZQ = 23;
  public static final int NOT = 10;
  public static final int AND = 12;
  public static final int EJEX = 53;
  public static final int IGUAL = 8;
  public static final int OR = 11;
  public static final int TITULO = 52;
  public static final int INCREMENTO = 14;
  public static final int DEFINIRGLOBALES = 45;
  public static final int NUM = 39;
  public static final int SUMA = 17;
  public static final int TYPEDEF = 42;
  public static final int MAIN = 3;
  public static final int IF = 28;
  public static final int ID = 43;
  public static final int PUNTO_COMA = 15;
  public static final int BOOLEAN = 44;
  public static final int EOF = 0;
  public static final int VALORES = 54;
  public static final int PARENTESIS_DER = 22;
  public static final int error = 1;
  public static final int COMA = 25;
  public static final int MENOR = 5;
  public static final int VOID = 2;
  public static final int NO_IGUAL = 9;
  public static final int SWITCH = 30;
  public static final int MAYOR = 4;
  public static final int ELSE = 29;
  public static final int LLAVE_DER = 24;
  public static final int SWITCH_BREAK = 33;
  public static final int PUNTO = 13;
  public static final int GRAFICABARRAS = 46;
  public static final int WHILE = 35;
  public static final int CORCHETE_IZQ = 26;
  public static final int DEFAULT = 32;
  public static final int MAYOR_IGUAL = 6;
  public static final int NEWVALOR = 48;
  public static final int MENOR_IGUAL = 7;
  public static final int DIVISION = 20;
  public static final int DOLAR = 47;
  public static final int CONSOLE = 37;
  public static final int DO = 36;
  public static final int MULTIPLICACION = 19;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "VOID",
  "MAIN",
  "MAYOR",
  "MENOR",
  "MAYOR_IGUAL",
  "MENOR_IGUAL",
  "IGUAL",
  "NO_IGUAL",
  "NOT",
  "OR",
  "AND",
  "PUNTO",
  "INCREMENTO",
  "PUNTO_COMA",
  "DOS_PUNTOS",
  "SUMA",
  "RESTA",
  "MULTIPLICACION",
  "DIVISION",
  "PARENTESIS_IZQ",
  "PARENTESIS_DER",
  "LLAVE_IZQ",
  "LLAVE_DER",
  "COMA",
  "CORCHETE_IZQ",
  "CORCHETE_DER",
  "IF",
  "ELSE",
  "SWITCH",
  "CASE",
  "DEFAULT",
  "SWITCH_BREAK",
  "FOR",
  "WHILE",
  "DO",
  "CONSOLE",
  "WRITE",
  "NUM",
  "STR",
  "CHAR",
  "TYPEDEF",
  "ID",
  "BOOLEAN",
  "DEFINIRGLOBALES",
  "GRAFICABARRAS",
  "DOLAR",
  "NEWVALOR",
  "GRAFICAPIE",
  "TITULOX",
  "TITULOY",
  "TITULO",
  "EJEX",
  "VALORES"
  };
}

